# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server.models.base_model_ import Model
from server import util


class ImportTxRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, hash: str=None):  # noqa: E501
        """ImportTxRequest - a model defined in Swagger

        :param hash: The hash of this ImportTxRequest.  # noqa: E501
        :type hash: str
        """
        self.swagger_types = {
            'hash': str
        }

        self.attribute_map = {
            'hash': 'hash'
        }
        self._hash = hash

    @classmethod
    def from_dict(cls, dikt) -> 'ImportTxRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ImportTxRequest of this ImportTxRequest.  # noqa: E501
        :rtype: ImportTxRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hash(self) -> str:
        """Gets the hash of this ImportTxRequest.


        :return: The hash of this ImportTxRequest.
        :rtype: str
        """
        return self._hash

    @hash.setter
    def hash(self, hash: str):
        """Sets the hash of this ImportTxRequest.


        :param hash: The hash of this ImportTxRequest.
        :type hash: str
        """
        if hash is None:
            raise ValueError("Invalid value for `hash`, must not be `None`")  # noqa: E501

        self._hash = hash
